services:
  postgres:
    image: postgres:15.3-bullseye
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - postgresdata:/var/lib/postgresql/data
  app:
    build:
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "$APP_PORT:$APP_PORT"
      - "$DEBUGPY_PORT:$DEBUGPY_PORT"
    env_file:
      - .env
    environment:
      PYDEVD_DISABLE_FILE_VALIDATION: "1"
      DEBUGPY_PORT: $DEBUGPY_PORT
    command: >
      bash -c "
      echo waiting for postgres to be ready... &&
      while ! nc -z postgres 5432; do sleep 1; done &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:$$APP_PORT"
volumes:
  postgresdata:
