FROM python:3.11.4-slim-bullseye

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt && \
rm /tmp/requirements.txt

COPY entrypoint.sh /app/entrypoint.sh
COPY ./src /app

CMD ./entrypoint.sh