FROM python:3.11.4-slim-bullseye

COPY requirements.txt /tmp/requirements.txt

RUN apt update && apt install -y netcat && \
rm -rf /var/lib/apt/lists/* && \
pip install -r /tmp/requirements.txt && \
rm /tmp/requirements.txt
